name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download
      run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip
    - name: Extract
      run: unzip ngrok.zip
    - name: Auth
      run: ./ngrok/ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: sudo sed -i 's/^#\(.*\)X11Forwarding.*/\1X11Forwarding yes/' /etc/ssh/sshd_config && sudo service ssh restart
    - run: sudo ufw allow 3389/tcp
    - run: sudo apt-get install -y xrdp
    - name: Set Password
      run: echo "ubuntu:P@ssw0rd!" | sudo chpasswd
    - name: Create Tunnel
      run: ./ngrok/ngrok tcp 3389
